### ISSUE TITLE
select for every asset

### ISSUE THREAD

**Issue by mariuz** [georgiev/rubyfb#13]
I get a select for every asset 

Started GET "/assets/rails.png" for 127.0.0.1 at 2012-04-06 21:46:14 +0300
   (29.3ms)  select first 1 cast(1 as smallint) from rdb$database
Served asset /rails.png - 304 Not Modified (0ms)
[2012-04-06 21:46:14] WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true

**Comment by georgiev** [comment]
You get this select for every connection checkout - that's how rubyfb checks connection validity

**Comment by mariuz** [comment]
then you can close the issue , if found that is just strange to connect to db for every single asset :)

I can use nginx for frontend and assets

**Comment by georgiev** [comment]
It's just the way the rails stack works - nothing to do with the rubyfb code.
