### ISSUE TITLE
After gem install keeps throwing error about rubyfb_lib.so

### ISSUE THREAD

**Issue by EddieDee** [georgiev/rubyfb#18]
This happened to me in linux, in Windows is working good.

[rake --tasks] rake aborted!
libruby19.so.1.9: cannot open shared object file: No such file or directory - /home/developer/.rvm/gems/ruby-1.9.3-p448@VnErpApi/gems/rubyfb-0.6.7/lib/rubyfb_lib.so
/home/developer/.rvm/gems/ruby-1.9.3-p448@VnErpApi/gems/rubyfb-0.6.7/lib/rubyfb.rb:4:in `require'
/home/developer/.rvm/gems/ruby-1.9.3-p448@VnErpApi/gems/rubyfb-0.6.7/lib/rubyfb.rb:4:in`<top (required)>'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in`block (2 levels) in require'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in`block in require'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in`require'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
/home/developer/projects/rails/VnErpApi/config/application.rb:7:in`<top (required)>'
/home/developer/projects/rails/VnErpApi/Rakefile:4:in `require'
/home/developer/projects/rails/VnErpApi/Rakefile:4:in`<top (required)>'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in`load_rakefile'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/application.rb:637:in `raw_load_rakefile'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/application.rb:94:in`block in load_rakefile'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/application.rb:93:in`load_rakefile'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/application.rb:77:in `block in run'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/application.rb:165:in`standard_exception_handling'
/home/developer/.rvm/gems/ruby-1.9.3-p448@global/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/home/developer/projects/rails/VnErpApi/bin/rake:4:in`<main>'

**Comment by EddieDee** [comment]
Another example with the test script:

require 'rubygems'
require 'rubyfb'
include Rubyfb

db = Database.new('test.gdb')

result:

/home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:51:in `require': libruby19.so.1.9: cannot open shared object file: No such file or directory - /home/developer/.rvm/gems/ruby-1.9.3-p448/gems/rubyfb-0.6.7/lib/rubyfb_lib.so (LoadError)
    from /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:51:in`require'
    from /home/developer/.rvm/gems/ruby-1.9.3-p448/gems/rubyfb-0.6.7/lib/rubyfb.rb:4:in `<top (required)>'
    from /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:116:in`require'
    from /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:116:in `rescue in require'
    from /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:122:in`require'
    from testfb.rb:2:in `<main>'

**Comment by georgiev** [comment]
On Mon, 05 Aug 2013 00:33:57 -0700
Pricestatrd notifications@github.com wrote:

> Another example with the test script:
> 
> require 'rubygems'
> require 'rubyfb'
> include Rubyfb
> 
> db = Database.new('test.gdb')
> 
> result:
> 
> /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:51:in
> `require': libruby19.so.1.9: cannot open shared object file: No such
> file or directory
> - /home/developer/.rvm/gems/ruby-1.9.3-p448/gems/rubyfb-0.6.7/lib/rubyfb_lib.so
>   (LoadError)
>   from /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:51:in
>   `require'
>   from /home/developer/.rvm/gems/ruby-1.9.3-p448/gems/rubyfb-0.6.7/lib/rubyfb.rb:4:in
>   `<top (required)>'
>   from /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:116:in
>   `require'
>   from /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:116:in
>   `rescue in require'
>   from /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:122:in
>   `require' from testfb.rb:2:in`<main>'
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/georgiev/rubyfb/issues/18#issuecomment-22090944

What is ldd saying?
ldd /home/developer/.rvm/gems/ruby-1.9.3-p448/gems/rubyfb-0.6.7/lib/rubyfb_lib.so

## 

Georgiev georgiev@heatds.com
Heat Ltd.

**Comment by EddieDee** [comment]
Good info:
linux-gate.so.1 =>  (0xb771e000)
    libfbclient.so.2 => /usr/lib/i386-linux-gnu/libfbclient.so.2 (0xb761f000)
    libruby19.so.1.9 => not found
    libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb75db000)
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb7428000)
    libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb7423000)
    libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb7408000)
    /lib/ld-linux.so.2 (0xb771f000)

**Comment by EddieDee** [comment]
I just did a:

sudo ln -s /home/developer/.rvm/rubies/ruby-1.9.3-p448/lib/libruby.so.1.9 /usr/lib/libruby19.so.1.9

I know it can't be the best approach to it but until now everything is working

**Comment by georgiev** [comment]
It will work, but linking system wide library to your home one is not a good thing. Something is messed up with your rvm install - try to fix that to avoid future issues.
Anyway I'm glad you managed to get it work and narrowed down the source of the problem.
