### ISSUE TITLE
Connection option hash

### ISSUE THREAD

**Issue by tuxjobs** [georgiev/rubyfb#5]
Hi,
is this the propper way to give the attribut sql_role_name to the connect satement?
Couldn't find any example how the hash should look like...

db = Database.new('test-server.org:C:\DB\test.fdb')
db.connect('Username', 'Passwort',{SQL_ROLE_NAME => "DB_USERS"})

**Comment by georgiev** [comment]
Your code is correct  - that's the way for passing options to connection

**Comment by tuxjobs** [comment]
hmm... if i use 'SQL_ROLE_NAME' as key - i get 'uninitialized constant SQL_ROLE_NAME'

SQL_ROLE_NAME => uninitialized constant SQL_ROLE_NAME
"SQL_ROLE_NAME" => no implicit conversion from nil to integer
:sql_role_name => no implicit conversion from nil to integer

**Comment by georgiev** [comment]
Using fully qualified constant name Rubyfb::Connection::SQL_ROLE_NAME should help.

**Comment by tuxjobs** [comment]
thx - worked

**Comment by georgiev** [comment]
Ok - closing
